#Задание 2: Докеризировать API

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bdlike45
      POSTGRES_DB: flask_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      PG_USER: postgres
      PG_PASSWORD: bdlike45
      PG_DB: flask_db
      PG_HOST: db
      PG_PORT: 5432
    depends_on:
      - db

volumes:
  postgres_data: