#Задание 2: Докеризировать API

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DB: ${PG_DB}
      PG_HOST: db
      PG_PORT: ${PG_PORT}
    depends_on:
      - db
    command: >
      sh -c "python create_tables.py && python server.py"
      
volumes:
  postgres_data: